#%RAML 1.0
title: Movie Ticket Booking Service
version: v1
baseUri: /

types:
  Booking:
    properties:
      date: datetime
      time: datetime
      venue: string
      movie: string
      cinemaRoom: string
      number of Tickets: number
      amount: number

resourceTypes:
  GET:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>

  POST:
    post:
      body:
        application/json:
          type: <<item>>
        
      responses:
        201:
          body:
            application/json:
              type: <<item>>


/booking:
  type:   { POST: {item : Booking} }

  /verify/{orderId}:
    type:  { GET: {item : Booking} }
